language: python

dist: trusty

python:
  - "2.7"

install:
  - pip install requests configargparse bcrypt
  - pip install coverage nose

script:
  - nosetests --with-coverage --cover-xml --cover-package=xclib

after_success:
  - bash <(curl -s https://codecov.io/bash)
