#!/usr/bin/php -f
<?php
if ($argc < 5 || $argc > 6) {
  print "Usage: generateTimeLimitedToken USER DOMAIN SECRET TTL [STARTTIME]\n";
  exit(1);
}
if ($argc == 5) {
  $argv[5] = null;
}
print generateUser($argv[1], $argv[2], $argv[3], $argv[4], $argv[5]) . "\n";

# Taken from https://github.com/nextcloud/jsxc.nextcloud/blob/master/lib/TimeLimitedToken.php#L7
# (without "public static")
function generateUser($node, $domain, $secret, $ttl = 60 * 60, $time = null)
{
  if (!isset($time) || $time === null) {
    $time = time();
  }
  $jid = $node. '@' . $domain;
  $expiry = $time + $ttl;
  $version = hex2bin('00');
  $secretID = substr(hash('sha256', $secret, true), 0, 2);
  $header = $secretID.pack('N', $expiry);
  $challenge = $version.$header.$jid;
  $hmac = hash_hmac('sha256', $challenge, $secret, true);
  $token = $version.substr($hmac, 0, 16).$header;
  // format as "user-friendly" base64
  $token = str_replace('=', '', strtr(
  base64_encode($token),
   'OIl',
  '-$%'
  ));
  return $token;
}
