#!/bin/sh
set -e

# Create users, groups if needed
if ! groups xcauth > /dev/null 2>&1
then
  adduser --system --disabled-password --disabled-login --group --home ${DBDIR} --gecos "XMPP Cloud Authentication" ${USER}
fi

# User exists, but not group of xcauth -> add group
if [ `groups prosody 2> /dev/null | grep -v xcauth | wc -l` -gt 0 ]
then
  adduser prosody xcauth
fi

if [ `groups ejabberd 2> /dev/null | grep -v xcauth | wc -l` -gt 0 ]
then
  adduser ejabberd xcauth
fi

#DEBHELPER#
